// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SemtSkoru.Infrastructure.Persistence;

#nullable disable

namespace SemtSkoru.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916102925_EnableRowLevelSecurityOnDistrictSummaries")]
    partial class EnableRowLevelSecurityOnDistrictSummaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SemtSkoru.Domain.AirQualityReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("AqiIndex")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReadingTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("AirQualityReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.DistrictSummary", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScoreSignature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("DistrictSummaries", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.GreenSpaceReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("NearestParkDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("NearestParkName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("GreenSpaceReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.HealthAccessReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WardCount")
                        .HasColumnType("integer");

                    b.Property<double>("WeightedHealthIndex")
                        .HasColumnType("double precision");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("HealthAccessReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.Neighborhood", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Neighborhoods", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.ParkingReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("AverageAvailabilityRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("FacilityCount")
                        .HasColumnType("integer");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("ParkingReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.TrafficReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("AverageSpeedKmh")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("TrafficReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.TransitAccessReading", b =>
                {
                    b.Property<string>("NeighborhoodId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("StopCount")
                        .HasColumnType("integer");

                    b.Property<double>("StopDensityPerKm2")
                        .HasColumnType("double precision");

                    b.HasKey("NeighborhoodId");

                    b.ToTable("TransitAccessReadings", (string)null);
                });

            modelBuilder.Entity("SemtSkoru.Domain.AirQualityReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("AirQualityReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("AirQualityReadingNeighborhoodId");

                            b1.ToTable("AirQualityReadings");

                            b1.WithOwner()
                                .HasForeignKey("AirQualityReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("SemtSkoru.Domain.GreenSpaceReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("GreenSpaceReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("GreenSpaceReadingNeighborhoodId");

                            b1.ToTable("GreenSpaceReadings");

                            b1.WithOwner()
                                .HasForeignKey("GreenSpaceReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("SemtSkoru.Domain.HealthAccessReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("HealthAccessReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("HealthAccessReadingNeighborhoodId");

                            b1.ToTable("HealthAccessReadings");

                            b1.WithOwner()
                                .HasForeignKey("HealthAccessReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("SemtSkoru.Domain.ParkingReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("ParkingReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("ParkingReadingNeighborhoodId");

                            b1.ToTable("ParkingReadings");

                            b1.WithOwner()
                                .HasForeignKey("ParkingReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("SemtSkoru.Domain.TrafficReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("TrafficReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("TrafficReadingNeighborhoodId");

                            b1.ToTable("TrafficReadings");

                            b1.WithOwner()
                                .HasForeignKey("TrafficReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("SemtSkoru.Domain.TransitAccessReading", b =>
                {
                    b.OwnsOne("SemtSkoru.Domain.DataSourceMetadata", "Source", b1 =>
                        {
                            b1.Property<string>("TransitAccessReadingNeighborhoodId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Cadence")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Cadence");

                            b1.Property<DateTimeOffset>("FetchedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("FetchedAt");

                            b1.Property<DateTimeOffset>("LastSuccessfulSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastSuccessfulSyncAt");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PublishedAt");

                            b1.Property<string>("SourceLicense")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceLicense");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("SourceName");

                            b1.Property<string>("SourceUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("TransitAccessReadingNeighborhoodId");

                            b1.ToTable("TransitAccessReadings");

                            b1.WithOwner()
                                .HasForeignKey("TransitAccessReadingNeighborhoodId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
